version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: communalis_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: communalis_api
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGODB_URI: mongodb://mongo:27017/communalis
      JWT_SECRET: ${JWT_SECRET:-changeme_secret}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000,http://localhost:4200}
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  mongo_data:
  uploads:
